version: '3.7'
services:
  selenium:
    container_name: selenium_api
    build:
      context: ./selenium
      dockerfile: Dockerfile
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4000:4000